name: Salesforce LWC + Apex CI/CD

on:
  push:
    branches:
      - main
    paths:
      - "force-app/main/default/lwc/**"
      - "force-app/main/default/classes/**"

  pull_request:
    branches:
      - main
    paths:
      - "force-app/main/default/lwc/**"
      - "force-app/main/default/classes/**"

jobs:
  test-and-deploy:
    name: Test and Deploy
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Verify Node.js
        run: |
          echo "Node version:"
          node --version

          echo "NPM version:"
          npm --version

      - name: Install Salesforce CLI
        run: |
          npm install --global @salesforce/cli@latest

      - name: Verify Salesforce CLI
        run: |
          echo "Node:"
          node --version

          echo "Salesforce CLI:"
          sf --version

          echo "SF location:"
          which sf

      - name: Create JWT Key
        shell: bash
        run: |
          printf '%s\n' '${{ secrets.SF_JWT_KEY }}' > server.key
          chmod 600 server.key

      - name: Authenticate Salesforce
        shell: bash
        run: |
          sf org login jwt \
            --client-id "${{ secrets.SF_CONSUMER_KEY }}" \
            --jwt-key-file server.key \
            --username "${{ secrets.SF_USERNAME }}" \
            --instance-url "https://login.salesforce.com" \
            --alias MyDevOrg

      - name: Verify Salesforce Org
        run: |
          sf org display \
            --target-org MyDevOrg

      - name: Validate Salesforce Deployment
        run: |
          sf project deploy start \
            --source-dir force-app \
            --target-org MyDevOrg \
            --test-level RunLocalTests \
            --wait 30 \
            --dry-run

      - name: Deploy to Salesforce
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          sf project deploy start \
            --source-dir force-app \
            --target-org MyDevOrg \
            --test-level RunLocalTests \
            --wait 30

      - name: Cleanup
        if: always()
        run: |
          rm -f server.key
